#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

if [ -f $OPENSHIFT_HOMEDIR/mysql/LICENSE ]
then
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/smart_lock/smart_lock/manage.py syncdb --noinput'"
    python "$OPENSHIFT_REPO_DIR"wsgi/smart_lock/smart_lock/manage.py syncdb --noinput

    echo "Run Develop Server in background ....."
    python "$OPENSHIFT_REPO_DIR"wsgi/smart_lock/smart_lock/manage.py runserver 0.0.0.0:3435
    bg
    disown -h
fi
